services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
    volumes:
      - ./01_api/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  api:
    build: ./01_api
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: movies
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build: ./02_frontend
    environment:
      API_HOST: http://api:3001
    depends_on:
      - api
    ports:
      - "3000:3000"
