services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
    volumes:
      - ./01_api/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  api:
  build: ./01_api
  environment:
    DB_HOST: db
    DB_USER: root
    DB_PASSWORD: root
    DB_NAME: movies
  depends_on:
    db:
      condition: service_healthy
  entrypoint: ["sh", "-c", "sleep 20 && node index.js"]
  ports:
    - "3001:3001"


  frontend:
    build: ./02_frontend
    environment:
      NEXT_PUBLIC_API_HOST: http://api:3001
    depends_on:
      api:
        condition: service_started
    ports:
      - "3000:3000"
